print("\nSelected Components:")
        print(f"CPU: {selected_components.CPU} || Price: {allocation['CPU']}")
        print(f"GPU: {selected_components.GPU} || Price: {allocation['GPU']}")
        print(f"RAM: {selected_components.RAM} || Price: {allocation['RAM']}")
        print(f"Storage: {selected_components.Storage} || Price: {allocation['Storage']}")
        print(f"Motherboard: {selected_components.Motherboard} || Price: {allocation['Motherboard']}")
        print(f"PSU: {selected_components.PSU} || Price: {allocation['PSU']}")